### ISSUE TITLE
Settings -> Skills -> Add Skills -> Missing Validation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#206]
Please apply the validation we spoke about.

**Comment by KPSbuttar** [comment]
@bartmika Hi sir can you please add validations of any type you want and update skill_set.py file  with your code here: https://github.com/over55/workery-django/blob/master/workery/tenant_api/serializers/skill_set.py 
like this so that i get all required and other validation errors from API then will use this api errors and CREATE UI of both RED BOX errors and INLINE errors into pages like this. 

Same for Issue #134 please add validations and update serializers/order.py so will use api errors to create errors UI in Frontend html.

Thanks

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done sir JS and HTML part of validation is done now only API validation file needs to updated once you finish here:  https://github.com/over55/workery-django/blob/master/workery/tenant_api/serializers/skill_set.py
All validations will work.

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, I will implement this now.

**Comment by bartmika** [comment]
![screen shot 2018-05-29 at 7 41 17 pm](https://user-images.githubusercontent.com/5767602/40691101-57b7fb70-6378-11e8-9344-8eb472469b61.png)

Okay implemented validation. All you have to do to finish this ticket is to make sure you have error text in the insurance requirements.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done
