### ISSUE TITLE
Edit commercial client is missing fields

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#353]
**Summary:**
When editing a commercial client I cannot see all the fields.  
When adding there are more fields, such as company name, etc
https://london.workery.ca/en/clients/create/commercial

When editing, it is far less:
exmaple URL https://london.workery.ca/en/clients/summary/detail/23390/edit/

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its because their is no update page added for Commercial Client. This one where fields are missing is for Residential client only. So sir please add commercial client update page then will add all UI and other validation ui into both update pages as in both new latest work is missing. Thanks
