### ISSUE TITLE
(17) when complete_and_unpaid then how do we cancel?

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#425]
Currently if a job has been "completed and paid", you cannot cancel it - please add ability to cancel jobs which have been completed and either paid or not.

**Comment by rodolfomartinez** [comment]
I think this needs to be discussed within the office, because how would we limit abuse?

**Comment by rodolfomartinez** [comment]
Note: this should be for "complete_and_unpaid" and should only be accessible by managers

**Comment by rodolfomartinez** [comment]
At a URL like this (in financials)
https://london.workery.ca/en/financials/unpaid-jobs/detail/24427/?page=1

Can we please add an "Unassign" and "Close Job" button - which do the following:
1. Unassign- this reopens the job and puts it back into an "unassigned" state, removing it from financials
2. Close Job - this moves the job from complete and unpaid into "Cancelled" (no option for successful completion)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond may you please QA this ticket and close this when verified?

**Comment by RaymondO55** [comment]
Feature works but should be removed for "Paid" jobs to prevent abuse. Feature should only be available "Completed and Unpaid" jobs. 

Discussed workflow with Rodolfo last week and we came to conclusion that a job should never need to be changed from "Completed and Paid" because orders should never reach that status without some extreme mistakes made.

**Comment by bartmika** [comment]
@RaymondO55 Okay confirmed, may you please verify this issue can be closed? Thanks!
