### ISSUE TITLE
Paid Jobs Dropping Skill Sets

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#510]
When jobs are marked as Completed and Paid the job removes the Skill Set as shown in the following report.

![associate report - skill](https://user-images.githubusercontent.com/41381131/44533063-abbda980-a6c2-11e8-8ed9-f82212718d2d.png)
 
This is a major problem for running reports as paid jobs will not show up in skill reports. 

![skill set report](https://user-images.githubusercontent.com/41381131/44533630-f5f35a80-a6c3-11e8-91f2-2bef66dfdea6.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, thank for the detailed steps, I was able to confirm a major bug and I patched it up for the work order table and other tables which use the `ManyToManyField` such as: Customer, Staff, Associates and Partners. This bug affected fields like tags, vehicles, etc.

Now that this major bug fix was made, we have another problem -the problem is those skill sets where override and lost permanently, I am unable to retrieve them.

I would like to purpose to your team the following solutions to handle the permanent loss:

1. Just move on ahead and not worry about it.

2. I can enable editing of closed jobs for `management staff` users and your team may go in and manually update the skill sets based on the job description and comments.

3. Yourself, or a fellow teammate may provide me a `CSV` list of paid jobs and their skill sets and I will make sure those jobs will have the skill sets again.

Please advise what decision your team makes and I apologize again.

@rodolfomartinez @SusanFaiarley FYI
