### ISSUE TITLE
Auto Remove from Alerts NOT working?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#557]
**Summary:**
Associates are being removed from Alerts/Announcements before the specified due dates

**Comment by bartmika** [comment]
@rodolfomartinez I will implement emailing of the backend ETL which is responsible for deleting away messages. Hopefully it will help us diagnose the issue and also perhaps improve your business processes?

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I believe I may have fixed this issue. May your team please monitor this issue and let me know if you confirm it has been fixed. The issue was the delete code, it should work now. Also in addition I've added code which will email me for every automatic deletion. I will update it to email over55 once this issue is closed.

**Comment by bartmika** [comment]
Hey @rodolfomartinez can you close this issue?
