### ISSUE TITLE
Office News Bulletin Deleting Posts

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#627]
Posts made on the bulletin board are being deleted, seemingly after 72 hours, would it be possible to change this to only being deleted manually?

I am not sure if this is a bug, or a "feature"

**Comment by bartmika** [comment]
@KHynds Having looked through the code, here is the conclusion:

- There is no background process which deletes the bulletin board items every 72 hours
- I believe it might be an individual which accidentally deleted the news.
- Currently all frontline staff, managers and executives are allowed to delete a bulletin board item
- Deletes are not archived but permanently deleted so we don't know who deleted the item.

To fix this issue, we have the following options. Please let me know how you would like me to proceed:

1. Keep permissions as is, but implement deletions to go to archive and we have a record of who deleted this bulletin board announcement

2. Keep the system the way it works but restrict frontline staff from being able to delete a bulletin board item.

3. Restrict deletions from frontline staff and implement some-sort of archiving feature instead of permanent delete.

**Comment by rodolfomartinez** [comment]
I would be in favour of option 1.

**Comment by KHynds** [comment]
I agree with Rodolfo. Option 1.
