### ISSUE TITLE
All Client's "How did they discover us?" Changed to "Other"

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#639]
It appears all of our clients are now listed as discovering us by other.

New clients added appear appropriately, but pulling the new short report is showing ~16,000 "other" and a single "Friends and family" the  friend and family showing was added after the implementation of the new reports.

Also, the long report is showing no client's in 2019.

**Comment by bartmika** [comment]
Hi @KHynds,

There was a bug found, it appears there was no datetime range filtering. I added it in now so you shouldn't see so many records.

Another issue I cannot do about is that there are quite a bit about "other" choices because that's the way the data was inputted. I have added a "OLD" field and "NEW" field in the long form report so you can compare the old fields and the new. You will see quite a bit are "other".

Another potential issue I'd like your help with is the "join date". These reports are based on the user's join date and I noticed some users did not have this information inputted. Can you confirm the most recent users have had that field inputted?

Thanks!

**Comment by rodolfomartinez** [comment]
@bartmika can you clarify around "join date" for clients?

**Comment by bartmika** [comment]
@KHynds @rodolfomartinez I believe it has something to do with the "join date" that was automatically set by the system, instead it should have been set by the staff. If we go through and fix the join date for the range of clients, this report will automatically work.

**Comment by KHynds** [comment]
@bartmika Any idea how I can find what this range of clients is?

Previously to a couple weeks ago the join date was not a field whatsoever, and must've been filled in automatically in the back end.

I assume when you implemented the join date there was a short period when the join date was manual, yet not a required field?
