### ISSUE TITLE
Split 7 Day Follow up & Survey into Two Tasks

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#651]
**SUmmary:**
We would like to split 7 day Follow up and the Survey into two separate tasks. Can discuss further

**Comment by RaymondO55** [comment]
Hi @bartmika I have the details on how we would like to achieve this. This will involve editing old task pages as well as implement an addtional task into the system. New terminology will be included to communicate a clearer task for the volunteers. I will go through the changes page by page with images for clarification. @rodolfomartinez look over this and give the Bart the green light to proceed if it looks good

**48-Hour Follow Up**

- Change the name of this task from [48 hour follow up] to [Meeting Verification] to better communicate and organise the purpose of this task. 
- The name change should be reflected on **all** pages that has the old verbiage
*Note*
Instructions on how to deal with the [48 hour follow up tasks] tab in the tasks page will be covered below, make no changes to it at this stage.

![48hrtask](https://user-images.githubusercontent.com/41381131/58118402-b912b080-7bce-11e9-9f71-3b489fbceacb.png)
![48hrlist](https://user-images.githubusercontent.com/41381131/58118420-c465dc00-7bce-11e9-9cee-e7957b69e90e.png)

**New Task: Completion Verification**

- With Completion Survey being split into two parts, a new task for needs to be created. Here are the things that need to be included:
      - Task Description: Change the task description to "Please call the Associate and confirm that they have completed this job for the client"
      - The summary table on the task page needs to display the following fields: [Description] [Job #] [Client Name] [Client Address] [Associate Name] [Associate Phone Number] [Job Description] and a hyperlink to [Job Comments]
      - The task date should be set to 3 days after the [Client Meeting Date] taken from the [Meeting Verification] task (Formerly 48hr Follow Up). If this field was left blank it should default to the date the task was processed (Today's date). Currently defaults to the [Assignment Date] which has been causing a few problems in operations
      - [Completion Date] Should be a mandatory field

- *Task Process. Here's the flow chart for how this task should operate:*
  - Task opens with a table summary followed by a radio button field prompting the volunteer [Did you successfully contact the Associate?] with "Yes" and "No" as the options. Mandatory field

- If "Yes" is selected
   - The [Was the job successfully completed by the Associate?] radio button field appears. Mandatory field
   - Process functions the same as how the current [Survey] task operates with the following changes:
        - Remove the [Was a survey conducted?] field
        - [Completion Date] field should be mandatory
    - Once the task is processed, the job's status updates to [Completed and Unpaid] and a corresponding [Survey] task is created for the job 

- If "No" is selected"
  - Volunteer leaves comment about selection (Left message for Associate etc)
  - Once the task is processed, the task is postponed to the next work day (24hrs)

![CompletionVerification page](https://user-images.githubusercontent.com/41381131/58183166-d69e5380-7c7c-11e9-87a7-258ca8ab5153.png)

![Completion Verfication Task](https://user-images.githubusercontent.com/41381131/58119758-c2e9e300-7bd1-11e9-9376-8a004d0ac9b8.png)

**Survey Task**

With the separation of completion and survey the [Survey] task needs to be changed to reflect the process.

- The task date should be set to 2 days after the [Completion Date] collected from the [Completion Verification] task which is mandatory
- The summary table needs to display the following fields: [Description] [Client Name] [Client Address] [Client Phone Number] [Associate Name] [Job Description] and a hyperlink to [Job Comments]
- The only field required for this task is the [Was a survey conducted field]? with the usual process associated with that field happening. If "Yes" Then 5 survey questions appear, Elseif "No" the survey becomes a null value for the job.
- Add a [Postpone Button] to this page as well as it will be used for operations in training rather than over complicating the system.
- This task and process should be executable whether the job is marked as [Completed and Unpaid] or [Completed and Paid]. This task should not alter the status of the job at all

![Survey Task Page](https://user-images.githubusercontent.com/41381131/58187719-54665d00-7c85-11e9-8fc7-ba5739662ce2.png)

**Verification Task Tab**

The tab marked as [48 hour follow up tasks] needs to be altered and re-purposed. The purpose of this task list is to organise tasks that require the volunteer to call the associates such that a volunteer only needs to make one call to an associate and complete multiple tasks. With the new [Completion Verification] task and renamed [Meeting Verification] task Here are the following changes to be implemented:

- Change the name of the tab to [Verification Tasks]
- The tab will include all [Meeting Verification] and [Completion Verification] tasks as these are the tasks that require our volunteers to call associates
- The list should have the following fields: [Task Date] (Due Date) [Task Type] [Client Name] [Associate Name]
- The list should be sorted by [Associate Name] first then [Task Date] as the secondary sort. This seems counter-intuitive but the purpose of this list is to group tasks that can be completed with one call to an associate and should be sorted by associate for ease of use.

![Verification Task Tab](https://user-images.githubusercontent.com/41381131/58193965-4408af00-7c92-11e9-8537-7c20951fdd72.png)
